networks:
  app-network:

services:
  node:
    image: node:20.15-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: npm run dev --host
    networks: 
      - app-network
  
  proxy:
    image: nginx:1.27
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - app-network